[package]

name = "flaky-data-structures"
version = "0.1.0"
authors = [ "dsyang92@gmail.com" ]

[[lib]]

name = "structures"


[dependencies.quickcheck]
git = "https://github.com/BurntSushi/quickcheck"

[dependencies.quickcheck_macros]
git = "https://github.com/BurntSushi/quickcheck"
